/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_LDNetDiagnoService_LDNetTraceRoute */

#ifndef _Included_com_netease_LDNetDiagnoService_LDNetTraceRoute
#define _Included_com_netease_LDNetDiagnoService_LDNetTraceRoute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netease_LDNetDiagnoService_LDNetTraceRoute
 * Method:    startJNICTraceRoute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_breakpad_nativecreash_NativeCrash_init
  (JNIEnv *, jobject, jstring);
JNIEXPORT void JNICALL Java_com_breakpad_nativecreash_NativeCrash_crash
        (JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_breakpad_nativecreash_NativeCrash_crashThread
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
